#!/bin/sh
# Use this to generate the website. Paths are hardcoded to my pc.

for f in $(find -name \*.md | cut -d / -f 2-); do
	echo BU $f
	umka conv.um template.html $f "$(cat $f | pandoc -f markdown -t html)" > $(echo $f | cut -d . -f 1).html
done

